### ISSUE TITLE
'ascii' codec can't decode byte 0xac in position 2: ordinal not in range(128)

### ISSUE THREAD

**Issue by Ryan-Shz** [bytedance/tailor#12]
~/Desktop/memory » python3 tailor/library/src/main/python/encode.py -i 1669016124948.hprof -o 1669016124948-out.hprof
'ascii' codec can't decode byte 0xac in position 2: ordinal not in range(128)
decompress failed at: 18/602572

decode异常，帮忙看看是什么原因？

**Comment by shentianzhou** [comment]
必现的吗？

**Comment by wxingda** [comment]
遇到同样的问题了
