### ISSUE TITLE
不开启压缩，到处的 hprof 打不开

### ISSUE THREAD

**Issue by aheadlcx** [bytedance/tailor#14]
case 1 
Tailor.dumpHprofData(path, 【true】);
拿到的 hprof ，还原之后，可以正常打开。

case 2
Tailor.dumpHprofData(path, 【false】);
直接打开，失败。
decode 还原也失败。

**Comment by shentianzhou** [comment]
不开启压缩时，也要先还原，再打开。但还原的脚本需要做一些修改，跳过解压缩步骤
