### ISSUE TITLE
Android4.4test制造的OOM，dump出来decode.py解析不过

### ISSUE THREAD

**Issue by qgnie** [bytedance/tailor#2]
invalid literal for int() with base 16: ''
![image](https://user-images.githubusercontent.com/32289765/102203727-e7b85080-3f03-11eb-9bfd-536b18039958.png)
![image](https://user-images.githubusercontent.com/32289765/102203786-f7d03000-3f03-11eb-9bcd-a90d19c1c7f5.png)

test制造OOM方法：Integer[] a = new Integer[10000000]再将其加入到一个静态成员变量中(Android9上正常)

**Comment by shentianzhou** [comment]
更新下儿最新的脚本试试看

**Comment by qgnie** [comment]
仍旧有类似问题：
![image](https://user-images.githubusercontent.com/32289765/102575177-91c6f100-412d-11eb-99e4-fba8262166e4.png)

我感觉并不是decode.py脚本的问题，而是Android4.4(HTC D820ts, Android4.4.4)存在某种问题，通过Tailor dump出来hprof文件仅仅几MB, 我使用原生的Debug.dumpHprofData命令可得到正常hprof文件

**Comment by shentianzhou** [comment]
这个提示是当前python版本没有from_bytes函数，python版本要3.5以上, 例如：python3 decode.py xxx

**Comment by shentianzhou** [comment]
4.4上的这个问题，麻烦提供下源文件，我分析下儿什么原因

**Comment by qgnie** [comment]
文件如下:
[1609408159.hprof.zip](https://github.com/bytedance/tailor/files/5714975/1609408159.hprof.zip)

**Comment by shentianzhou** [comment]
问题已经验证确实存在，已经修复
原因是：4.4上移除了HPROF_ROOT_FINALIZING & HPROF_ROOT_REFERENCE_CLEANUP，但实际dump快照时还是会遇到这两种tag，机型原因。https://android.googlesource.com/platform/art/+/73e66f7%5E!/
