### ISSUE TITLE
获取到的文件使用python还原不了

### ISSUE THREAD

**Issue by dingqiqi** [bytedance/tailor#4]
python3 /Users/dingqiqi/Desktop/tailor-master/library/src/main/python/verify.py -i /Users/dingqiqi/Desktop/log/1.hprof 
'ascii' codec can't decode byte 0x9c in position 1: ordinal not in [range(128)]

python3 /Users/dingqiqi/Desktop/tailor-master/library/src/main/python/decode.py /Users/dingqiqi/Desktop/log/2.hprof target.hprof
usage: decode.py [-h] [-i INPUT] [-o OUTPUT]
decode.py: error: unrecognized arguments: /Users/dingqiqi/Desktop/log/2.hprof target.hprof

**Comment by YouJZ** [comment]
'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte

**Comment by shentianzhou** [comment]
参数错误
/Users/dingqiqi/Desktop/tailor-master/library/src/main/python/decode.py -i /Users/dingqiqi/Desktop/log/2.hprof -o target.hprof

**Comment by shentianzhou** [comment]
你本地的python版本是多少？方便的话贴下儿无法还原的快照文件

**Comment by bill-lia** [comment]
'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)

**Comment by YouJZ** [comment]
> 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte

我使用Python脚本是对应之前版本的，同步更新下就好了

**Comment by shentianzhou** [comment]
OK
