### ISSUE TITLE
支持x86吗？

### ISSUE THREAD

**Issue by easternHong** [bytedance/tailor#9]

**Comment by shentianzhou** [comment]
理论上是支持的，可以直接试试，x86没这需求没有针对性处理过

**Comment by kyze8439690** [comment]
目前 [代码](https://github.com/bytedance/tailor/blob/master/library/build.gradle#L14) 中已经加了filter，导致不生成x86的so，无法使用

**Comment by shentianzhou** [comment]
不支持，hook代码需要额外支持x86才可以
